name: Build
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache

      - uses: subosito/flutter-action@v1
        with:
          channel: stable

      - name: Swap android/app/src/main, decode key and properties, build app
        run: >
          for i in {1..${{ secrets.RESTAURANT_COUNT }}} 
            do 
              
              flutter pub get
              if [ ${{ github.ref }} = "refs/heads/main" ]
              then
                flutter build apk --release --dart-define=restaurantId="${{ secrets.RESTAURANT_IDS }}[i]" --dart-define=restaurantName="${{ secrets.RESTAURANT_NAMES }}[i]" --dart-define=endpoint="${{ secrets.GRAPHQL_ENDPOINT }}"
              fi
              if [ ${{ github.ref }} = "refs/heads/dev" ]
              then
                flutter build apk -t lib/main.dev.dart --release --dart-define=restaurantId="${{ secrets.RESTAURANT_IDS }}[i]" --dart-define=restaurantName="${{ secrets.RESTAURANT_NAMES }}[i]" --dart-define=endpoint="${{ secrets.GRAPHQL_ENDPOINT }}"
              fi
              done

      - uses: actions/upload-artifact@v2
        with:
          name: order.apk
          path: build/app/outputs/flutter-apk/app-release.apk
